config/routes.rb
Tacomquem::Application.routes.draw do
  resources :lends do
    resources :reminders
  end

  devise_for :users

  resources :friendships, only: [:index, :create, :destroy]

  root :to => 'lends#index'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id
  
  belongs_to :friend, :class_name => "User"
  
  before_destroy :write_friends_name  
  
  def write_friends_name
    all_lends = Lend.where(user_id: self.user_id, friend_id: self.friend_id)
    friend = User.find(self.friend_id)
    all_lends.each { |lend| lend.update_attributes(friend_id: nil, friend_name: friend.email) }
  end
  
end

app/models/lend.rb
class Lend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  has_many :reminders, dependent: :destroy
  
  validates_presence_of :friend_name, message: 'cant be blank', :if => Proc.new { |a| a.friend_id.blank? }
  validates_presence_of :friend_id, message: 'cant be blank', :if => Proc.new { |a| a.friend_name.blank? }
  
  attr_accessor :use_text
  attr_accessible :friend_id, :friend_name, :item, :use_text
  
  def use_text
    !friend_id && !self.new_record?
  end
  
  
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  attr_accessible :due_in, :lend_id
  
  belongs_to :lend
  
  validates :due_in, :lend_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :friends, :through => :friendships
  has_many :friendships, dependent: :destroy
  has_many :lends, dependent: :destroy
  
  scope :without, lambda { |id| where('id not in (?)', id) }
  
  
  def self_and_friends
    list = self.friends.collect(&:id)
    list << self.id
  end
  
  def to_s
    email
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  respond_to :html
  
  def index
    @all_users = User.without(current_user.self_and_friends)
    @friends = current_user.friends
    
  end
  
  def create
    already_friend = !current_user.friendships.where(friend_id: params[:friend_id]).empty?
    logger.info already_friend
    if already_friend
      flash[:notice] = "Friend already added."
    else
      @friendship = current_user.friendships.new(friend_id: params[:friend_id])
      flash[:notice] = "Friend was successfully added." if @friendship.save
    end

    respond_with(@friendship) do |format|
      format.html { redirect_to friendships_path }
    end
  end
  
  def destroy  
    @friendship = current_user.friendships.find_by_friend_id(params[:id])  
    @friendship.destroy 
    flash[:notice] = "Friendship cancelled."
     
    redirect_to friendships_url
  end
  
end

app/controllers/lends_controller.rb
class LendsController < ApplicationController
  # GET /lends
  # GET /lends.json
  def index
    @lends = current_user.lends

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lends }
    end
  end

  # GET /lends/1
  # GET /lends/1.json
  def show
    @lend = Lend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lend }
    end
  end

  # GET /lends/new
  # GET /lends/new.json
  def new
    @lend = Lend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lend }
    end
  end

  # GET /lends/1/edit
  def edit
    @lend = current_user.lends.find(params[:id])
  end

  # POST /lends
  # POST /lends.json
  def create
    @lend = current_user.lends.build(params[:lend])

    respond_to do |format|
      if @lend.save
        format.html { redirect_to lends_path, notice: 'Lend was successfully created.' }
        format.json { render json: @lend, status: :created, location: @lend }
      else
        format.html { render action: "new" }
        format.json { render json: @lend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lends/1
  # PUT /lends/1.json
  def update
    @lend = Lend.find(params[:id])

    respond_to do |format|
      if @lend.update_attributes(params[:lend])
        format.html { redirect_to lends_path, notice: 'Lend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lends/1
  # DELETE /lends/1.json
  def destroy
    @lend = Lend.find(params[:id])
    @lend.destroy

    respond_to do |format|
      format.html { redirect_to lends_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_filter :find_lend
  
  def new
    @reminder = @lend.reminders.new
  end

  def create
    @reminder = @lend.reminders.create(params[:reminder])

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to lends_path, notice: 'Reminder was successfully created.' }
        format.json { render json: @reminder, status: :created, location: @reminder }
      else
        format.html { render action: "new" }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def find_lend
    @lend = current_user.lends.find(params[:lend_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def link_to_destroy(url, html_options = {})
    html_options.reverse_merge!(:data => { :confirm => 'Are you sure?' }, :method => :delete, :class => "btn btn-mini btn-danger")
    link_to 'delete', url, html_options
  end
  
  def gravatar_tag(email, options = {})
    email = Digest::MD5.hexdigest(email)
    image_tag "http://www.gravatar.com/avatar/#{email}?size=#{options[:size]}", options
  end
  
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/lends_helper.rb
module LendsHelper
  
  def reminder_counter(lend)
    reminders = lend.reminders
    content_tag(:span, reminders.count, :class => "badge badge-error") if reminders.count > 0
  end
  
end

app/views/friendships/index.html.erb
<h2>Adicionar amigos</h2>

<% if @all_users %>
  <% @all_users.each do |user| %>
    <p>
      <%= user %>
      <%= link_to 'add as friend', friendships_path(friend_id: user.id), method: :post, class: 'btn btn-success btn-mini' %>
    </p>
  <% end %>
<% end %>

<hr />

<h2>Lista de amigos</h2>

<% if @friends %>
  <% @friends.each do |friend| %>
    <p>
      <%= friend %>
      <%= link_to_destroy friendship_path(id: friend.id) %>
    </p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'shared/navbar' if user_signed_in? %>

  <div class="container">
    
    <div class="row">
      <div class="span9">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">×</a>
            <%= msg %>
          </div>
        <% end %>
        
        <%= yield %>
      </div>
      <div class="span3">
        <h2>Sidebar</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
</body>
</html>

app/views/lends/_form.html.erb
<%= form_for lend, :html => { :class => 'form-horizontal' } do |f| %>
  
  <%= f.text_field :item, :class => 'text_field span4', placeholder: 'O que você emprestou?' %>
  
  <div id="text_or_friend">
    <div id="use_text_friend">
      <%= f.text_field :friend_name, :class => 'text_field', placeholder: 'Pra quem?' %>
    </div>
    <div id="select_friend">
      <%= collection_select(:lend, :friend_id, current_user.friends, :id, :email, :prompt => 'Pra quem?') %>
    </div>
  </div>
  
  <span>
    <%= f.check_box :use_text %> outra pessoa
  </span>
  
  <%= f.submit nil, :class => 'btn btn-success span2' %>

<% end %>

app/views/lends/edit.js.erb
$("#new_lend").html("<%= escape_javascript( render("form", :lend => @lend ) ) %>");

<% if @lend.use_text %>
  $('#select_friend').hide()
<% else %>
  $('#use_text_friend').hide()
<% end %>

app/views/lends/index.html.erb
<%- model_class = Lend.new.class -%>

<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th><%= model_class.human_attribute_name(:friend_name) %></th>
      <th><%= model_class.human_attribute_name(:friend_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lends.each do |lend| %>
      <tr>
        <td><%= lend.item %></td>
        <td><%= lend.friend_name %></td>
        <td><%= lend.friend %></td>
        <td><%=l lend.created_at, format: :short %></td>
        <td><%= reminder_counter(lend) %> <%= link_to 'lembrete', new_lend_reminder_path(lend) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lend_path(lend), :class => 'btn btn-mini', remote: true %>
          <%= link_to_destroy lend_path(lend) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h2>Novo empréstimo</h2>

<div id="new_lend">
  <%= render 'form', :lend => current_user.lends.build  %>
</div>

app/views/lends/new.html.erb
<%- model_class = @lend.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/lends/show.html.erb
<%- model_class = @lend.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:user_id) %>:</strong><br>
  <%= @lend.user_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:item) %>:</strong><br>
  <%= @lend.item %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:friend_name) %>:</strong><br>
  <%= @lend.friend_name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:friend_id) %>:</strong><br>
  <%= @lend.friend_id %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lends_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lend_path(@lend), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lend_path(@lend),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/reminders/new.html.erb
<%= form_for [@lend, @reminder] do |f| %>
    <%= f.date_select :due_in %>
    <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Com quem que tá?</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'Minhas coisas', lends_path %></li>
          <li><%= link_to 'Amigos', friendships_path %></li>
        </ul>
        <ul class="nav pull-right">
          <li class="dropdown">
            <a id="my_profile" class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= gravatar_tag current_user.email, :size => 20 %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'perfil' %></li>
              <li class="divider"></li>
              <li><%= link_to 'sair', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>